### ISSUE TITLE
ST_BOUNDARY generates error in BigQuery

### ISSUE THREAD

**Issue by JK-Richardson** [CartoDB/carto-spatial-extension#54] opened 2021-04-05 07:29 UTC
Hi. I am using the bqcartoeu UDFs and have a table with H3 cell values generated from point data. I want to visualize different statistics on these cells, for example, number of observations per cell. I am trying to generate the geometry for the cells using:

`select bqcartoeu.h3.ST_BOUNDARY(bqcartoeu.h3.H3_FROMHEX(col_with_h3_hex_string))`

This gives an error:

`ST_GeogFromText failed: Invalid polygon loop: Edge 5 crosses edge 7 `

Unfortunately, I cannot localize which H3 values are causing the error, but I want to ask if the SAFE prefix could be added to the UDF where you are calling ST_GeogFromText.

I guess I am thinking it would make sense here?

https://github.com/CartoDB/carto-spatial-extension/blob/afb66d77dde3f1773a9bb877bd793cfcac30ae46/h3/bq/sql/ST_BOUNDARY.sql#L32

Thanks!

**Comment by vdelacruzb** [comment] 2021-04-05 08:22
Hi @JK-Richardson,  thanks for noticing this issue. We are working on adding this fix right now. Keep you updated.
Kind regards!

**Comment by aswinramakrishnan** [comment] 2021-04-05 12:53
we got this error while using this function as well - jslibs.h3.ST_H3_BOUNDARY(h3). 

`ST_GeomFromGeoJSON` failed: Invalid polygon loop: Edge 5 crosses edge 7`

**Comment by vdelacruzb** [comment] 2021-04-05 14:24
@aswinramakrishnan you are right. The old jslibs contained the same implementation than:
`bqcarto/bqcartoeu.h3. ST_BOUNDARY`. 
I strongly recommend moving to bqcarto instead of jslibs. It will be receiving all our fixes as well as upcoming UDFs and modules.

The fix is on review. It should be ready tomorrow, as I'm waiting for approval and it will have to be deployed into production.

**Comment by aswinramakrishnan** [comment] 2021-04-05 15:19
Thanks @vdelacruzb. It would take a lot of time for us to do this migration and there are teams to teams dependency on jslibs.

**Comment by martejpad** [comment] 2021-04-05 15:30
hi @aswinramakrishnan! Could you share what functionality from jslibs are you using? Is it only H3? If so, it should be really easy to migrate as most functions keep their signature and simply change their name. Let us know and we'll try to help. Thanks!!

**Comment by aswinramakrishnan** [comment] 2021-04-05 16:10
Yes @martejpad, we use most of H3 functions. 

As far I see, we are using these and there can be others too.  
1. jslibs.h3.geoToH3(lat, lon, level)
2. jslibs.h3.ST_H3_POLYFILLFROMGEOG(ST_GEOGFROMTEXT(wkt), level)
3. jslibs.h3.ST_H3_BOUNDARY(h3)

I have few questions as well - 
1. deprecation date/stop maintainence date on jslibs
2. output of these queries gives different h3 indexes. 
SELECT jslibs.h3.ST_H3(ST_GEOGPOINT(10,10),11)            - 8b58e0682d69fff
SELECT bqcarto.h3.ST_ASH3(ST_GEOGPOINT(10,10),11)   - 627563881704103935

**Comment by vdelacruzb** [comment] 2021-04-06 13:34
Hi @aswinramakrishnan  in case you want to adapt the functions to the new implementation maybe it can be done fast with a text editor that allows to replace texts in multiple files at the same time, the next replacement should be done:
1. jslibs.h3.geoToH3 -> bqcarto.h3.LONGLAT_ASH3
2. jslibs.h3.ST_H3_POLYFILLFROMGEOG -> bqcarto.h3.ST_ASH3_POLYFILL
3. jslibs.h3.ST_H3_BOUNDARY -> bqcarto.h3.ST_BOUNDARY

Regarding your questions:
1. jslibs has already been deprecated. So it won't be maintained. We will keep it accessible thought in order to avoid breaking the work of everybody that could be using it still.
2. Actually both indexes are the same but the first one is an hexademical represantation (STRING) and the second a INT representation. We created the functions H3_ASHEX and H3_FROMHEX to move from one to the other. Working with ints, it's in general more efficient that's why we did this change. 
On this last point we are going back to use hexadecimal by default though: https://github.com/CartoDB/carto-spatial-extension/pull/58
Once that PR is merged you will see that both return the same. It also covers the issue with the SAFE prefix.

**Comment by JK-Richardson** [comment] 2021-04-07 13:10
How do I see when this has been deployed to BigQuery UDFs in the bqcarto and bqcartoeu project?

I am depending on the bqcartoeu project so I hope this will be updated as well.

**Comment by vdelacruzb** [comment] 2021-04-07 14:23
Hi @JK-Richardson finally we are planning to deploy it this Friday 9th of April. This will also make H3 to be hexadecimal as default so you won't need to use `bqcartoeu.h3.H3_FROMHEX` anymore.
I will let you know as soon as it's in production.

We are also thinking in how to improve feedback and notify everybody about new releases.

**Comment by vdelacruzb** [comment] 2021-04-07 14:25
* I have reopened the issue. It will be closed once the fix is in production.

**Closed** 2021-04-09 11:42 UTC

**Comment by vdelacruzb** [comment] 2021-04-09 11:44
@JK-Richardson @aswinramakrishnan 
The changes have been deployed already to production. 

- ST_BOUNDARY now use the SAFE prefix.
- bqcarto.h3 uses hexadecimals by default.

**Comment by JK-Richardson** [comment] 2021-04-09 12:16
@vdelacruzb Excellent and thanks to you and the team for your work :-)

As a related question, do you or anybody else know the specific cause of the error I mentioned at the beginning of this thread? I am wondering why the call to ST_BOUNDARY would generate an invalid polygon? Is this a bug in the H3 library or an issue where some H3 cells hash to something that cannot generate a valid geometry? It seems like all H3 addresses should generate valid polygons but maybe I don't understand completely how H3 works. Thanks!

**Comment by martejpad** [comment] 2021-04-09 12:24
Hi @JK-Richardson @aswinramakrishnan: as a side note, we have a new Discord channel dedicated to the spatial extension (former jslibs) https://discord.gg/4U5XVrGyqW. Would love you to join us there 😃

**Comment by vdelacruzb** [comment] 2021-04-09 12:51
@JK-Richardson regarding your questions.
It's the first time we come across that issue. I have just added the SAFE prefix with no luck on reproducing the issue. I have tried different cases containing H3 hexagons, pentagons, random and null values, not valid indexes, also reading chunks of h3 tables, using polyfills and didn't get that. That's why it would be super interesting to find the H3 values that gave you problems, as we also wanted to add a unit test that check that it's covered. Don't hesitate to share with us if you find some data that generates the issue.

I doubt it's a bug in H3 library, I'm reviewing our functions and see that we are concatenating the vertices returned by the H3 function h3ToGeoBoundary in order to a create WKT. I will take a deeper look to this because it seems that we might be adding another point to an already close loop polygon.
